# -*- coding: utf-8 -*-
"""deepFace.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xZCDLAuBD4CkgIssaIvkjgrJOGmLoKVg
"""

pip install deepface

from deepface import DeepFace
import cv2
import matplotlib.pyplot as plt
import numpy as np
from skimage.io import imread
import pickle
import json
import pandas as pd

#ler imagens de uma vez só
total_de_imagens = 20
endereco = '/content/dataSet-triste/'
imagens = []
for i in range(total_de_imagens):
  imagem = imread(endereco+'img'+str(i+1)+'.jpg')
  imagens.append(imagem)

figura = plt.figure(figsize=(15, 8))
for i in range(total_de_imagens):
  figura.add_subplot(4, 5, i+1)
  plt.imshow(imagens[i])
  plt.title(i)
plt.show()

try:
  print('IMPRIMINDO ANÁLISE GERAL DE TODAS AS EMOÇÕES')
  lista_todas_emocoes_geral = []
  for i in range(total_de_imagens):
    analise = DeepFace.analyze(imagens[i], enforce_detection=False)
    analise
    emocao_geral = analise['emotion']
    lista_todas_emocoes_geral.append(emocao_geral)
    print(emocao_geral)
except:
  print("No face detected")

#analise da emoção dominante
try:
  print('IMPRIMINDO EMOÇÃO DOMINANTE')
  for i in range(total_de_imagens):
      analise = DeepFace.analyze(imagens[i], enforce_detection=False)
      analise
      emocao_dominante = analise['dominant_emotion']
      print('img'+str(i+1)+':'+emocao_dominante)
except:
  print('No face detected')

#salvando em JSON emocoes gerais
with open('/content/dados/triste.json', 'w') as fp:
    json.dump(lista_todas_emocoes_geral, fp)

with open('/content/dados/triste.json', 'r') as fp:
    data = json.load(fp)
print(data)

#converter JSON para EXCEL
with open('/content/dados/triste.json') as json_file:
    data = json.load(json_file)

df = pd.DataFrame(data)
df.to_excel('/content/dados/triste.xlsx')

"""# Nova seção"""