# -*- coding: utf-8 -*-
"""fer.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HBGI315uOgszz9JkIJ8hgxM4eCTWuG4U
"""

pip install fer

from fer import FER
import cv2
import matplotlib.pyplot as plt
import numpy as np
from skimage.io import imread
import pickle
import json
import pandas as pd

#ler imagens de uma vez só
total_de_imagens = 20
endereco = '/content/dataSet-surpresa/'
imagens = []
for i in range(total_de_imagens):
  imagem = imread(endereco+'img'+str(i+1)+'.jpg')
  imagens.append(imagem)
#test_image = plt.imread("/content/euSorrindo.jpeg")

figura = plt.figure(figsize=(15, 8))
for i in range(total_de_imagens):
  figura.add_subplot(4, 5, i+1)
  plt.imshow(imagens[i])
  plt.title(i)
plt.show()

detector = FER(mtcnn=True)

try:
  print('IMPRIMINDO ANÁLISE GERAL DE TODAS AS EMOÇÕES')
  lista_todas_emocoes_geral = []
  for i in range(total_de_imagens):
    analise = detector.detect_emotions(imagens[i])
    lista_todas_emocoes_geral.append(analise)
    print(analise)
except:
  print('No face detected')
#captured_emotions = emo_detector.detect_emotions(test_image)

lista_simplificada = []
for i in range(total_de_imagens):
  emotion, score = detector.top_emotion(imagens[i])
  result = emotion, score
  lista_simplificada.append(result)
  print(result)

#salvando em JSON emocoes gerais
with open('/content/dados/surpresa.json', 'w') as fp:
    json.dump(lista_simplificada, fp)

with open('/content/dados/surpresa.json', 'r') as fp:
    data = json.load(fp)
print(data)

#converter JSON para EXCEL
with open('/content/dados/surpresa.json') as json_file:
    data = json.load(json_file)

df = pd.DataFrame(data)
df.to_excel('/content/dados/surpresa.xlsx')